# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-09 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_user_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to='dashboard.Description'),
        ),
    ]
